<?php

/**
 * @file
 * Primary module hooks for SPREP Whereabouts module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\sprep_whereabouts\Plugin\Field\MyComputedField;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function sprep_whereabouts_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type)
{
  if ($entity_type->id() == 'user') {
    $fields['my_computed_field'] = BaseFieldDefinition::create('string')
      ->setLabel(t('My computed field'))
      ->setName('My computed field')
      ->setDescription(t('My computed field description.'))
      ->setComputed(TRUE)
      ->setClass(MyComputedField::class);
  }
}
